name: multi-gpu-test
image: mosaicml/pytorch:2.2.2_cu121-python3.11-ubuntu20.04

integrations:
- integration_type: git_repo
  git_repo: srijitcn/ext_mct
  git_branch: main # use your branch
  ssh_clone: true # Should be true if using a private repo

command: |
  cd ext_mct
  echo "MASTER_ADDR:$MASTER_ADDR"
  echo "MASTER_PORT:$MASTER_PORT"  
  pip install torch transformers accelerate evaluate scikit-learn mlflow
  python multigpu.py

compute:
  gpus: 16
  cluster: r8z11