name: multi-gpu-test
image: mosaicml/pytorch:2.2.2_cu121-python3.11-ubuntu20.04

integrations:
- integration_type: git_repo
  git_repo: srijitcn/ext_mct
  git_branch: main # use your branch
  ssh_clone: true # Should be true if using a private repo

command: |
  cd ext_mct
  export MASTER_ADDR=127.0.0.0
  export MASTER_PORT=12355
  pip install torch transformers accelerate evaluate scikit-learn mlflow
  
  export CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7
  torchrun --nproc_per_node 8 multigpu.py

compute:
  gpus: 8
  cluster: r8z11