name: multi-gpu-test
image: mosaicml/pytorch:2.2.2_cu121-python3.11-ubuntu20.04

integrations:
- integration_type: git_repo
  git_repo: srijitcn/ext_mct
  git_branch: main # use your branch
  ssh_clone: true # Should be true if using a private repo

command: |
  cd ext_mct
  pwd
  ls -al
  pip install torch transformers accelerate evaluate scikit-learn mlflow
  python multi_gpu.py

compute:
  gpus: 8
  cluster: r8z11